---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cert-manager-083
  region: eu-central-1
  version: "1.23"
availabilityZones:
- eu-central-1a
- eu-central-1b
managedNodeGroups:
- name: general
  labels:
    role: general
  instanceType: t3.small
  desiredCapacity: 2
  minSize: 1
  maxSize: 10
  volumeSize: 20




#     To create this cluster, provide config to the eksctl.

# eksctl create cluster -f eks.yaml --profile eksctl

#     Similar command to delete the cluster.

# eksctl delete cluster -f eks.yaml --profile eksctl