---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mitruk-me
  namespace: staging
spec:
  isCA: false
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: mitruk.me
  dnsNames:
  - mitruk.me
  - www.mitruk.me
  secretName: mitruk-me-io-key-pair
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  issuerRef:
    name: mitruk-me-ca
    kind: ClusterIssuer
    group: cert-manager.io
