---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80   #  # Map this service port to a different port on the host some times ( 502 Bad Gateway nginx, if was mistake in targetPort and port is difrent than targetPort )
      #targetPort: 80 # The service targetPort should match the container port exposed by the pod in deployment. if not ( 503 Service Temporarily Unavailable nginx)!!!
  type: LoadBalancer

---