---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-cluster-049
  region: eu-central-1
  version: "1.28"
availabilityZones: 
- eu-central-1a
- eu-central-1b
managedNodeGroups:
- name: on-demand
  labels:
    role: on-demand
  instanceType: t2.small
  desiredCapacity: 2
  volumeSize: 20
  


# eksctl create cluster -f eks.yaml
# eksctl delete cluster --name=my-cluster-049 --region=eu-central-1