---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-cluster-072
  region: eu-central-1
  version: "1.23"
availabilityZones:
- eu-central-1a
- eu-central-1b
managedNodeGroups:
- name: general
  labels:
    role: general
  instanceType: t3.medium
  minSize: 2
  maxSize: 10
  desiredCapacity: 2
  volumeSize: 20
